version: "3"
services:
    db:
        image: mysql
        container_name: ${PROJECT_NAME}_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - herewego

    phpmyadmin:
        image: phpmyadmin
        container_name: ${PROJECT_NAME}_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - herewego

    maildev:
        image: maildev/maildev
        container_name: ${PROJECT_NAME}_maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "8081:80"
        restart: always
        networks:
            - herewego

    www:
        build: php
        container_name: ${PROJECT_NAME}_www
        ports:
          - "3000:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ${LOCAL_PROJECT_ROOT}:/var/www/html
        restart: always
        networks:
            - herewego

networks:
    herewego:

volumes:
    db-data: